server:
  port: 80
  tomcat:
    uri-encoding: utf-8
    max-threads: 300
  context-path: /

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 0
  cache:
    ehcache:
      config: classpath:config/ehcache.xml
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/test_demo
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  freemarker.allow-request-override: false
  freemarker.cache: true
  freemarker.check-template-location: true
  freemarker.charset: UTF-8
  freemarker.content-type:  text/html
  freemarker.expose-request-attributes: false
  freemarker.expose-session-attributes: false
  freemarker.expose-spring-macro-helpers: false
  mvc.view.prefix: classpath:/templates/
  mvc.view.suffix: .html

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mpp.model

logging:
  config: classpath:config/logback.xml
  level: info